### ISSUE TITLE
Previous Experience

### ISSUE THREAD

**Issue by jrconlin** [hildjj/project-shutdown#1]
I've had to shut down several services in the past. Here's the rubric that I've used.

1) Clear Communications and lede time.
Make sure that you provide enough time to notify customers and users impacted. Use all the feedback mechanisms possible. 
Determine the appropriate amount of time that the project should live (for languages, this is usually 1 year, mid size projects or services at least 1 month. "Cut and run" is never a great idea, but I've done it in the past.) Select a date and stick to it.

Use compiler warnings, start-up logging messages, response meta data, etc. to let folk know that the service is going away. Presume that no one will read your toot / blog post / README / CHANGELOG.

2) Have one source of information. 
Point folks to a single source of truth. I've usually made this the README for the repo, but a page offered up by the service (e.g. `example.com/__shutdown__` or whatever works.)

3) Offer a replacement (if possible)
Can they run a "stand alone" version of your service until they can get a replacement?
Is there someone who offers something similar? 
Unless you're purposefully burning bridges, don't just flip the switch and walk away. Devs and SRE have remarkably long memories. 

4) Purposefully degrade the service prior to shutdown. 
Two weeks prior to end of life, introduce slowness to make Ops suddenly aware that there's a problem. Nothing gets attention like dropping metrics. Keep boosting the artificial delay as the clock winds down. 

Generally, the projects I've dealt with have never had binding SROs, so if you do, you want to make sure that you're legally clear to terminate the service. (The ones I've seen usually have a clause that allows a service provider to terminate with cause, provided that customers get notified in advance, but I can imagine some may not have thought about that.)

**Comment by hildjj** [comment]
Thanks.  I'll weave all of this into the right places in the docs, unless you'd like to send a PR.

**Comment by jrconlin** [comment]
I can send in a PR, but not until later tonight.
